-- themes: id/name/JSON/timestamps plus is_bundled to block DELETE on seeded
-- rows. PATCH still works on bundled themes (you can recolor in place);
-- DELETE returns 400. INSERT OR IGNORE lets a botched bundled theme
-- self-heal on next boot (delete the row, restart, seed re-inserts it).
-- Data blobs come from ST's default/content/themes/*.json run through the
-- compat migrator at build time — see scripts/bake-themes.ts.
CREATE TABLE themes (
  id            TEXT PRIMARY KEY,
  name          TEXT NOT NULL,
  data          TEXT NOT NULL DEFAULT '{}',         -- JSON ThemeData
  is_bundled    INTEGER NOT NULL DEFAULT 0,         -- 1 = seeded, can't DELETE
  created_at    INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at    INTEGER NOT NULL DEFAULT (unixepoch())
);

INSERT OR IGNORE INTO themes (id, name, data, is_bundled) VALUES
  ('dark-lite', 'Dark Lite', '{"colors":{"body":"rgba(220, 220, 210, 1)","emphasis":"rgba(145, 145, 145, 1)","underline":"rgba(188, 231, 207, 1)","quote":"rgba(225, 138, 36, 1)","shadow":"rgba(0, 0, 0, 1)","blurTint":"rgba(23, 23, 23, 1)","chatTint":"rgba(23, 23, 23, 1)","border":"rgba(0, 0, 0, 1)","userMesBlurTint":"rgba(30, 30, 30, 0.9)","botMesBlurTint":"rgba(30, 30, 30, 0.9)"},"layout":{"font_scale":1,"blur_strength":10,"shadow_width":2,"chat_width":50,"corner_radius":10,"message_density":1,"avatar_style":"circle","chat_display":"flat","font":""},"toggles":{"reduced_motion":false,"no_blur":true,"no_shadows":true,"compact_input":true,"timestamps":true,"model_icon":true,"message_ids":false,"token_count":false,"gen_timer":false,"hide_avatars":false,"expand_actions":false,"swipe_count_all":false},"custom_css":""}', 1),
  ('azure', 'Azure', '{"colors":{"body":"rgba(171, 198, 223, 1)","emphasis":"rgba(255, 255, 255, 1)","underline":"rgba(188, 231, 207, 1)","quote":"rgba(111, 133, 253, 1)","shadow":"rgba(0, 0, 0, 1)","blurTint":"rgba(23, 30, 33, 0.61)","chatTint":"rgba(23, 23, 23, 0)","border":"rgba(0, 0, 0, 0.5)","userMesBlurTint":"rgba(0, 28, 174, 0.2)","botMesBlurTint":"rgba(0, 13, 57, 0.22)"},"layout":{"font_scale":1,"blur_strength":11,"shadow_width":5,"chat_width":50,"corner_radius":10,"message_density":1,"avatar_style":"rectangle","chat_display":"bubbles","font":""},"toggles":{"reduced_motion":false,"no_blur":false,"no_shadows":false,"compact_input":false,"timestamps":true,"model_icon":false,"message_ids":true,"token_count":false,"gen_timer":true,"hide_avatars":false,"expand_actions":false,"swipe_count_all":false},"custom_css":""}', 1),
  ('cappuccino', 'Cappuccino', '{"colors":{"body":"rgba(235, 235, 235, 1)","emphasis":"rgba(230, 210, 190, 1)","underline":"rgba(205, 180, 160, 1)","quote":"rgba(165, 140, 115, 1)","shadow":"rgba(0, 0, 0, 0.3)","blurTint":"rgba(34, 30, 32, 0.95)","chatTint":"rgba(50, 45, 50, 0.75)","border":"rgba(80, 80, 80, 0.89)","userMesBlurTint":"rgba(34, 30, 32, 0.75)","botMesBlurTint":"rgba(34, 30, 32, 0.75)"},"layout":{"font_scale":1,"blur_strength":3,"shadow_width":1,"chat_width":50,"corner_radius":10,"message_density":1,"avatar_style":"circle","chat_display":"bubbles","font":""},"toggles":{"reduced_motion":false,"no_blur":false,"no_shadows":false,"compact_input":true,"timestamps":true,"model_icon":true,"message_ids":true,"token_count":false,"gen_timer":false,"hide_avatars":false,"expand_actions":false,"swipe_count_all":false},"custom_css":""}', 1),
  ('celestial-macaron', 'Celestial Macaron', '{"colors":{"body":"rgba(229, 175, 162, 1)","emphasis":"rgba(146, 147, 161, 1)","underline":"rgba(157, 215, 198, 1)","quote":"rgba(197, 202, 206, 1)","shadow":"rgba(0, 0, 0, 0.3)","blurTint":"rgba(23, 36, 55, 0.9)","chatTint":"rgba(18, 26, 40, 0.9)","border":"rgba(60, 74, 110, 0.93)","userMesBlurTint":"rgba(51, 67, 90, 0.7)","botMesBlurTint":"rgba(23, 36, 55, 0.75)"},"layout":{"font_scale":1,"blur_strength":10,"shadow_width":1,"chat_width":58,"corner_radius":10,"message_density":1,"avatar_style":"circle","chat_display":"bubbles","font":""},"toggles":{"reduced_motion":false,"no_blur":false,"no_shadows":true,"compact_input":true,"timestamps":true,"model_icon":false,"message_ids":true,"token_count":true,"gen_timer":true,"hide_avatars":false,"expand_actions":true,"swipe_count_all":false},"custom_css":""}', 1),
  ('dark-v1', 'Dark V 1.0', '{"colors":{"body":"rgba(207, 207, 197, 1)","emphasis":"rgba(145, 145, 145, 1)","underline":"rgba(145, 145, 145, 1)","quote":"rgba(198, 193, 151, 1)","shadow":"rgba(0, 0, 0, 0.9)","blurTint":"rgba(29, 33, 40, 0.9)","chatTint":"rgba(29, 33, 40, 0.9)","border":"rgba(0, 0, 0, 1)","userMesBlurTint":"rgba(29, 33, 40, 0.9)","botMesBlurTint":"rgba(29, 33, 40, 0.9)"},"layout":{"font_scale":1,"blur_strength":13,"shadow_width":2,"chat_width":55,"corner_radius":10,"message_density":1,"avatar_style":"circle","chat_display":"flat","font":""},"toggles":{"reduced_motion":true,"no_blur":false,"no_shadows":false,"compact_input":false,"timestamps":false,"model_icon":false,"message_ids":false,"token_count":false,"gen_timer":false,"hide_avatars":false,"expand_actions":false,"swipe_count_all":false},"custom_css":""}', 1);
